/* Do not edit! This file is autogenerated by MenuEdit on 7-8-16 15:49:56*/

#ifndef MENU_INTERPRETER_CONFIG_H
#define MENU_INTERPRETER_CONFIG_H

#define USE16BITADDR

#define MENU_DATASIZE 2142
#define MENU_OBJECTS_MAX 6
#define MENU_LIST_MAX 0
#define MENU_TEXT_MAX 27
#define MENU_CHECKBOX_MAX 0
#define MENU_RADIOBUTTON_MAX 0
#define MENU_GFX_MAX 0
#define MENU_MULTIGFX_MAX 0
#define MENU_ACTION_MAX 53

#define MENU_SCREEN_X 28
#define MENU_SCREEN_Y 5

#define MENU_ACTION_DisplayUpdateOff 1
#define MENU_ACTION_Dcf77Off 2
#define MENU_ACTION_Dcf77On 3
#define MENU_ACTION_ShowClockOn 4
#define MENU_ACTION_ShowAlarmOn 5
#define MENU_ACTION_ShowTimerOn 6
#define MENU_ACTION_ShowTemperatureOn 7
#define MENU_ACTION_ShowKeylockOn 8
#define MENU_ACTION_ShowDateOn 9
#define MENU_ACTION_AlarmDec 10
#define MENU_ACTION_AlarmInc 11
#define MENU_ACTION_AlarmNext 12
#define MENU_ACTION_TimerDec 13
#define MENU_ACTION_TimerInc 14
#define MENU_ACTION_TimerStart 15
#define MENU_ACTION_ShowDispbrightOn 16
#define MENU_ACTION_BrightDec 17
#define MENU_ACTION_BrightInc 18
#define MENU_ACTION_BrightAutoToggle 19
#define MENU_ACTION_BrightAlwaysOff 20
#define MENU_ACTION_BrightAlwaysOn 21
#define MENU_ACTION_ClockShowSecOff 22
#define MENU_ACTION_ClockShowSecOn 23
#define MENU_ACTION_SoundAutoOffDec 24
#define MENU_ACTION_SoundAutoOffInc 25
#define MENU_ACTION_SoundVolumeDec 26
#define MENU_ACTION_SoundVolumeInc 27
#define MENU_ACTION_SoundFreqDec 28
#define MENU_ACTION_SoundFreqInc 29
#define MENU_ACTION_RefreshDec 30
#define MENU_ACTION_RefreshInc 31
#define MENU_ACTION_ShowVoltageOn 32
#define MENU_ACTION_ShowCurrentOn 33
#define MENU_ACTION_ShowChargedOn 34
#define MENU_ACTION_ShowLightOn 35
#define MENU_ACTION_ShowDCF77On 36
#define MENU_ACTION_Reboot 37
#define MENU_ACTION_ShowKeysOn 38
#define MENU_ACTION_ShowConsumptionOn 39
#define MENU_ACTION_ShowPerformanceOn 40
#define MENU_ACTION_ChargerDec 41
#define MENU_ACTION_ChargerInc 42
#define MENU_ACTION_Rs232Dec 43
#define MENU_ACTION_Rs232Inc 44
#define MENU_ACTION_BatCapDec 45
#define MENU_ACTION_BatCapInc 46
#define MENU_ACTION_LedCurrDec 47
#define MENU_ACTION_LedCurrInc 48
#define MENU_ACTION_CalRes46Dec 49
#define MENU_ACTION_CalRes46Inc 50
#define MENU_ACTION_Dcf77LevelDec 51
#define MENU_ACTION_Dcf77LevelInc 52

#define MENU_TEXT_DcfValue 0
#define MENU_TEXT_Clock 1
#define MENU_TEXT_Date 2
#define MENU_TEXT_Alarm 3
#define MENU_TEXT_Timer 4
#define MENU_TEXT_Temperature 5
#define MENU_TEXT_Brightness 6
#define MENU_TEXT_BrigthAlways 7
#define MENU_TEXT_ShowSecs 8
#define MENU_TEXT_SoundAutoOffTime 9
#define MENU_TEXT_SoundVolume 10
#define MENU_TEXT_SoundFreq 11
#define MENU_TEXT_Refresh 12
#define MENU_TEXT_InputVoltage 13
#define MENU_TEXT_ChargerCurrent 14
#define MENU_TEXT_ChargerCharged 15
#define MENU_TEXT_ChargerMode 16
#define MENU_TEXT_Light 17
#define MENU_TEXT_KeyAdValue 18
#define MENU_TEXT_Rs232Debug 19
#define MENU_TEXT_ConsumptionTotal 20
#define MENU_TEXT_Performance 21
#define MENU_TEXT_BatCap 22
#define MENU_TEXT_LedCurrent 23
#define MENU_TEXT_CalibRes 24
#define MENU_TEXT_Dcf77Level 25
#define MENU_TEXT_Keylock 26






#define MENU_USE_LABEL
#define MENU_USE_SUBWINDOW
#define MENU_USE_WINDOW
#define MENU_USE_SHORTCUT

#define MENU_USE_FONT_14
#define MENU_USE_FONT_15
#define MENU_USE_FONT_MAX 15
#define MENU_USE_UTF8

#define MENU_SDATA_5_1 1895
#define MENU_SDATA_35_1 1901
#define MENU_SDATA_36_1 1907
#define MENU_SDATA_3_1 1913
#define MENU_SDATA_33_1 1918
#define MENU_SDATA_34_1 1925
#define MENU_SDATA_62_1 1931
#define MENU_SDATA_7_1 1939
#define MENU_SDATA_39_1 1947
#define MENU_SDATA_40_1 1954
#define MENU_SDATA_41_1 1961
#define MENU_SDATA_42_1 1969
#define MENU_SDATA_43_1 1977
#define MENU_SDATA_44_1 1984
#define MENU_SDATA_1_1 1992
#define MENU_SDATA_51_1 2000
#define MENU_SDATA_61_1 2007
#define MENU_SDATA_59_1 2015
#define MENU_SDATA_4_1 2022
#define MENU_SDATA_29_1 2029
#define MENU_SDATA_28_1 2035
#define MENU_SDATA_31_1 2042
#define MENU_SDATA_52_1 2047
#define MENU_SDATA_53_1 2053
#define MENU_SDATA_68_1 2061
#define MENU_SDATA_70_1 2070
#define MENU_SDATA_72_1 2077
#define MENU_SDATA_73_1 2085
#define MENU_SDATA_76_1 2093
#define MENU_SDATA_56_1 2103
#define MENU_SDATA_67_1 2110
#define MENU_SDATA_64_1 2118
#define MENU_SDATA_65_1 2126
#define MENU_SDATA_66_1 2134

#endif

