/* Do not edit! This file is autogenerated by MenuEdit on 16-7-17 11:56:46*/

#ifndef MENU_INTERPRETER_CONFIG_H
#define MENU_INTERPRETER_CONFIG_H

#define USE16BITADDR

#define MENU_DATASIZE 3718
#define MENU_OBJECTS_MAX 6
#define MENU_LIST_MAX 0
#define MENU_TEXT_MAX 47
#define MENU_CHECKBOX_MAX 0
#define MENU_RADIOBUTTON_MAX 0
#define MENU_GFX_MAX 0
#define MENU_MULTIGFX_MAX 0
#define MENU_ACTION_MAX 106

#define MENU_SCREEN_X 28
#define MENU_SCREEN_Y 5

#define MENU_ACTION_DisplayUpdateOff 1
#define MENU_ACTION_Dcf77Off 2
#define MENU_ACTION_Dcf77On 3
#define MENU_ACTION_ShowClockOn 4
#define MENU_ACTION_ShowAlarmOn 5
#define MENU_ACTION_ShowAlarmadvancedOn 6
#define MENU_ACTION_ShowTimerOn 7
#define MENU_ACTION_ShowTemperatureOn 8
#define MENU_ACTION_PowersaveOn 9
#define MENU_ACTION_ShowDateOn 10
#define MENU_ACTION_AlarmDec 11
#define MENU_ACTION_AlarmInc 12
#define MENU_ACTION_AlarmNext 13
#define MENU_ACTION_AlarmAdvancedDec 14
#define MENU_ACTION_AlarmAdvancedInc 15
#define MENU_ACTION_AlarmAdvancedNext 16
#define MENU_ACTION_TimerDec 17
#define MENU_ACTION_TimerInc 18
#define MENU_ACTION_TimerStart 19
#define MENU_ACTION_ShowDispbrightOn 20
#define MENU_ACTION_ShowPowersavestartOn 21
#define MENU_ACTION_ShowPowersavestopOn 22
#define MENU_ACTION_ShowPowersaveweekOn 23
#define MENU_ACTION_BrightDec 24
#define MENU_ACTION_BrightInc 25
#define MENU_ACTION_BrightAutoToggle 26
#define MENU_ACTION_BrightAlwaysOff 27
#define MENU_ACTION_BrightAlwaysOn 28
#define MENU_ACTION_ClockShowSecOff 29
#define MENU_ACTION_ClockShowSecOn 30
#define MENU_ACTION_SummertimeAuto 31
#define MENU_ACTION_SummertimeOff 32
#define MENU_ACTION_SoundAutoOffDec 33
#define MENU_ACTION_SoundAutoOffInc 34
#define MENU_ACTION_SoundVolumeDec 35
#define MENU_ACTION_SoundVolumeInc 36
#define MENU_ACTION_SoundFreqDec 37
#define MENU_ACTION_SoundFreqInc 38
#define MENU_ACTION_RefreshDec 39
#define MENU_ACTION_RefreshInc 40
#define MENU_ACTION_Rfm12Dec 41
#define MENU_ACTION_Rfm12Inc 42
#define MENU_ACTION_Rfm12passkey100 43
#define MENU_ACTION_Rfm12passkey10 44
#define MENU_ACTION_Rfm12passkey1 45
#define MENU_ACTION_Rc5Dec 46
#define MENU_ACTION_Rc5Inc 47
#define MENU_ACTION_Rc5RecordUp 48
#define MENU_ACTION_PowersavestartDec 49
#define MENU_ACTION_PowersavestartInc 50
#define MENU_ACTION_PowersavestartNext 51
#define MENU_ACTION_PowersavestopDec 52
#define MENU_ACTION_PowersavestopInc 53
#define MENU_ACTION_PowersavestopNext 54
#define MENU_ACTION_PowersaveweekDec 55
#define MENU_ACTION_PowersaveweekInc 56
#define MENU_ACTION_PowersaveweekNext 57
#define MENU_ACTION_ShowVoltageOn 58
#define MENU_ACTION_ShowCurrentOn 59
#define MENU_ACTION_ShowChargedOn 60
#define MENU_ACTION_ShowLightOn 61
#define MENU_ACTION_ShowDCF77On 62
#define MENU_ACTION_Reboot 63
#define MENU_ACTION_ShowKeysOn 64
#define MENU_ACTION_ShowConsumptionOn 65
#define MENU_ACTION_ShowPerformanceOn 66
#define MENU_ACTION_PintestStart 67
#define MENU_ACTION_ShowLoggerOn 68
#define MENU_ACTION_ShowElapsedtimeOn 69
#define MENU_ACTION_ShowClockSetOn 70
#define MENU_ACTION_ShowRamOn 71
#define MENU_ACTION_ChargerChargedDec 72
#define MENU_ACTION_ChargerChargedInc 73
#define MENU_ACTION_ChargerDec 74
#define MENU_ACTION_ChargerInc 75
#define MENU_ACTION_Rs232Dec 76
#define MENU_ACTION_Rs232Inc 77
#define MENU_ACTION_BatCapDec 78
#define MENU_ACTION_BatCapInc 79
#define MENU_ACTION_LedCurrDec 80
#define MENU_ACTION_LedCurrInc 81
#define MENU_ACTION_CalRes46Dec 82
#define MENU_ACTION_CalRes46Inc 83
#define MENU_ACTION_Dcf77LevelDec 84
#define MENU_ACTION_Dcf77LevelInc 85
#define MENU_ACTION_LoggerPeriodDec 86
#define MENU_ACTION_LoggerPeriodInc 87
#define MENU_ACTION_Dcf77PeriodDec 88
#define MENU_ACTION_Dcf77PeriodInc 89
#define MENU_ACTION_FlickerWorkaroundOff 90
#define MENU_ACTION_FlickerWorkaroundOn 91
#define MENU_ACTION_TimeManualHourInc 92
#define MENU_ACTION_TimeManualMinInc 93
#define MENU_ACTION_TimeManualSecZero 94
#define MENU_ACTION_DateManualDayInc 95
#define MENU_ACTION_DateManualMonthInc 96
#define MENU_ACTION_DateManualYearInc 97
#define MENU_ACTION_ClockCalibDec 98
#define MENU_ACTION_ClockCalibInc 99
#define MENU_ACTION_ClockCalibAuto 100
#define MENU_ACTION_KeylockLeave 101
#define MENU_ACTION_Rc5RecordDisable 102
#define MENU_ACTION_Rc5RecordDown 103
#define MENU_ACTION_Rc5RecordLeft 104
#define MENU_ACTION_Rc5RecordRight 105

#define MENU_TEXT_DcfValue 0
#define MENU_TEXT_Clock 1
#define MENU_TEXT_Date 2
#define MENU_TEXT_Alarm 3
#define MENU_TEXT_Alarmadvanced 4
#define MENU_TEXT_Timer 5
#define MENU_TEXT_Temperature 6
#define MENU_TEXT_Brightness 7
#define MENU_TEXT_BrigthAlways 8
#define MENU_TEXT_ShowSecs 9
#define MENU_TEXT_Summertime 10
#define MENU_TEXT_SoundAutoOffTime 11
#define MENU_TEXT_SoundVolume 12
#define MENU_TEXT_SoundFreq 13
#define MENU_TEXT_Refresh 14
#define MENU_TEXT_Rfm12enabled 15
#define MENU_TEXT_Rfm12passkey 16
#define MENU_TEXT_Rc5enabled 17
#define MENU_TEXT_Powersavestart 18
#define MENU_TEXT_Powersavestop 19
#define MENU_TEXT_Powersaveweekdays 20
#define MENU_TEXT_InputVoltage 21
#define MENU_TEXT_ChargerCurrent 22
#define MENU_TEXT_ChargerCharged 23
#define MENU_TEXT_ChargerMode 24
#define MENU_TEXT_Light 25
#define MENU_TEXT_KeyAdValue 26
#define MENU_TEXT_Rs232Debug 27
#define MENU_TEXT_ConsumptionTotal 28
#define MENU_TEXT_Performance 29
#define MENU_TEXT_BatCap 30
#define MENU_TEXT_LedCurrent 31
#define MENU_TEXT_CalibRes 32
#define MENU_TEXT_Dcf77Level 33
#define MENU_TEXT_Pintest 34
#define MENU_TEXT_Logger 35
#define MENU_TEXT_Rebootcounter 36
#define MENU_TEXT_Elapsedtimemeter 37
#define MENU_TEXT_LoggerPeriod 38
#define MENU_TEXT_Dcf77Period 39
#define MENU_TEXT_FlickerWorkaround 40
#define MENU_TEXT_ClockCalibrate 41
#define MENU_TEXT_FreeRam 42
#define MENU_TEXT_Rc5up 43
#define MENU_TEXT_Rc5down 44
#define MENU_TEXT_Rc5left 45
#define MENU_TEXT_Rc5right 46






#define MENU_USE_BOX
#define MENU_USE_LABEL
#define MENU_USE_SUBWINDOW
#define MENU_USE_WINDOW
#define MENU_USE_SHORTCUT

#define MENU_USE_FONT_14
#define MENU_USE_FONT_15
#define MENU_USE_FONT_MAX 15
#define MENU_USE_UTF8

#define MENU_SDATA_5_1 3310
#define MENU_SDATA_35_1 3316
#define MENU_SDATA_78_1 3323
#define MENU_SDATA_36_1 3330
#define MENU_SDATA_3_1 3336
#define MENU_SDATA_33_1 3341
#define MENU_SDATA_34_1 3348
#define MENU_SDATA_62_1 3354
#define MENU_SDATA_86_1 3362
#define MENU_SDATA_7_1 3369
#define MENU_SDATA_39_1 3377
#define MENU_SDATA_40_1 3384
#define MENU_SDATA_106_1 3391
#define MENU_SDATA_41_1 3398
#define MENU_SDATA_42_1 3406
#define MENU_SDATA_43_1 3414
#define MENU_SDATA_44_1 3421
#define MENU_SDATA_80_1 3429
#define MENU_SDATA_105_1 3436
#define MENU_SDATA_81_1 3444
#define MENU_SDATA_83_1 3449
#define MENU_SDATA_84_1 3456
#define MENU_SDATA_85_1 3464
#define MENU_SDATA_1_1 3471
#define MENU_SDATA_51_1 3479
#define MENU_SDATA_61_1 3486
#define MENU_SDATA_59_1 3494
#define MENU_SDATA_4_1 3501
#define MENU_SDATA_29_1 3508
#define MENU_SDATA_28_1 3514
#define MENU_SDATA_31_1 3521
#define MENU_SDATA_52_1 3526
#define MENU_SDATA_53_1 3532
#define MENU_SDATA_68_1 3540
#define MENU_SDATA_70_1 3549
#define MENU_SDATA_72_1 3556
#define MENU_SDATA_73_1 3564
#define MENU_SDATA_76_1 3572
#define MENU_SDATA_92_1 3582
#define MENU_SDATA_93_1 3590
#define MENU_SDATA_100_1 3597
#define MENU_SDATA_101_1 3605
#define MENU_SDATA_108_1 3612
#define MENU_SDATA_109_1 3620
#define MENU_SDATA_112_1 3628
#define MENU_SDATA_114_1 3636
#define MENU_SDATA_116_1 3643
#define MENU_SDATA_118_1 3651
#define MENU_SDATA_120_1 3662
#define MENU_SDATA_123_1 3671
#define MENU_SDATA_56_1 3679
#define MENU_SDATA_67_1 3686
#define MENU_SDATA_64_1 3694
#define MENU_SDATA_65_1 3702
#define MENU_SDATA_66_1 3710

#endif

