/* Do not edit! This file is autogenerated by MenuEdit on 24-10-16 20:28:37*/

#ifndef MENU_INTERPRETER_CONFIG_H
#define MENU_INTERPRETER_CONFIG_H

#define USE16BITADDR

#define MENU_DATASIZE 2958
#define MENU_OBJECTS_MAX 6
#define MENU_LIST_MAX 0
#define MENU_TEXT_MAX 40
#define MENU_CHECKBOX_MAX 0
#define MENU_RADIOBUTTON_MAX 0
#define MENU_GFX_MAX 0
#define MENU_MULTIGFX_MAX 0
#define MENU_ACTION_MAX 82

#define MENU_SCREEN_X 28
#define MENU_SCREEN_Y 5

#define MENU_ACTION_DisplayUpdateOff 1
#define MENU_ACTION_Dcf77Off 2
#define MENU_ACTION_Dcf77On 3
#define MENU_ACTION_ShowClockOn 4
#define MENU_ACTION_ShowAlarmOn 5
#define MENU_ACTION_ShowAlarmadvancedOn 6
#define MENU_ACTION_ShowTimerOn 7
#define MENU_ACTION_ShowTemperatureOn 8
#define MENU_ACTION_PowersaveOn 9
#define MENU_ACTION_ShowDateOn 10
#define MENU_ACTION_AlarmDec 11
#define MENU_ACTION_AlarmInc 12
#define MENU_ACTION_AlarmNext 13
#define MENU_ACTION_AlarmAdvancedDec 14
#define MENU_ACTION_AlarmAdvancedInc 15
#define MENU_ACTION_AlarmAdvancedNext 16
#define MENU_ACTION_TimerDec 17
#define MENU_ACTION_TimerInc 18
#define MENU_ACTION_TimerStart 19
#define MENU_ACTION_ShowDispbrightOn 20
#define MENU_ACTION_ShowPowersavestartOn 21
#define MENU_ACTION_ShowPowersavestopOn 22
#define MENU_ACTION_ShowPowersaveweekOn 23
#define MENU_ACTION_BrightDec 24
#define MENU_ACTION_BrightInc 25
#define MENU_ACTION_BrightAutoToggle 26
#define MENU_ACTION_BrightAlwaysOff 27
#define MENU_ACTION_BrightAlwaysOn 28
#define MENU_ACTION_ClockShowSecOff 29
#define MENU_ACTION_ClockShowSecOn 30
#define MENU_ACTION_SoundAutoOffDec 31
#define MENU_ACTION_SoundAutoOffInc 32
#define MENU_ACTION_SoundVolumeDec 33
#define MENU_ACTION_SoundVolumeInc 34
#define MENU_ACTION_SoundFreqDec 35
#define MENU_ACTION_SoundFreqInc 36
#define MENU_ACTION_RefreshDec 37
#define MENU_ACTION_RefreshInc 38
#define MENU_ACTION_Rfm12Dec 39
#define MENU_ACTION_Rfm12Inc 40
#define MENU_ACTION_Rc5Dec 41
#define MENU_ACTION_Rc5Inc 42
#define MENU_ACTION_Rc5RecordUp 43
#define MENU_ACTION_PowersavestartDec 44
#define MENU_ACTION_PowersavestartInc 45
#define MENU_ACTION_PowersavestartNext 46
#define MENU_ACTION_PowersavestopDec 47
#define MENU_ACTION_PowersavestopInc 48
#define MENU_ACTION_PowersavestopNext 49
#define MENU_ACTION_PowersaveweekDec 50
#define MENU_ACTION_PowersaveweekInc 51
#define MENU_ACTION_PowersaveweekNext 52
#define MENU_ACTION_ShowVoltageOn 53
#define MENU_ACTION_ShowCurrentOn 54
#define MENU_ACTION_ShowChargedOn 55
#define MENU_ACTION_ShowLightOn 56
#define MENU_ACTION_ShowDCF77On 57
#define MENU_ACTION_Reboot 58
#define MENU_ACTION_ShowKeysOn 59
#define MENU_ACTION_ShowConsumptionOn 60
#define MENU_ACTION_ShowPerformanceOn 61
#define MENU_ACTION_PintestStart 62
#define MENU_ACTION_ShowLoggerOn 63
#define MENU_ACTION_ShowElapsedtimeOn 64
#define MENU_ACTION_ChargerDec 65
#define MENU_ACTION_ChargerInc 66
#define MENU_ACTION_Rs232Dec 67
#define MENU_ACTION_Rs232Inc 68
#define MENU_ACTION_BatCapDec 69
#define MENU_ACTION_BatCapInc 70
#define MENU_ACTION_LedCurrDec 71
#define MENU_ACTION_LedCurrInc 72
#define MENU_ACTION_CalRes46Dec 73
#define MENU_ACTION_CalRes46Inc 74
#define MENU_ACTION_Dcf77LevelDec 75
#define MENU_ACTION_Dcf77LevelInc 76
#define MENU_ACTION_KeylockLeave 77
#define MENU_ACTION_Rc5RecordDisable 78
#define MENU_ACTION_Rc5RecordDown 79
#define MENU_ACTION_Rc5RecordLeft 80
#define MENU_ACTION_Rc5RecordRight 81

#define MENU_TEXT_DcfValue 0
#define MENU_TEXT_Clock 1
#define MENU_TEXT_Date 2
#define MENU_TEXT_Alarm 3
#define MENU_TEXT_Alarmadvanced 4
#define MENU_TEXT_Timer 5
#define MENU_TEXT_Temperature 6
#define MENU_TEXT_Brightness 7
#define MENU_TEXT_BrigthAlways 8
#define MENU_TEXT_ShowSecs 9
#define MENU_TEXT_SoundAutoOffTime 10
#define MENU_TEXT_SoundVolume 11
#define MENU_TEXT_SoundFreq 12
#define MENU_TEXT_Refresh 13
#define MENU_TEXT_Rfm12enabled 14
#define MENU_TEXT_Rc5enabled 15
#define MENU_TEXT_Powersavestart 16
#define MENU_TEXT_Powersavestop 17
#define MENU_TEXT_Powersaveweekdays 18
#define MENU_TEXT_InputVoltage 19
#define MENU_TEXT_ChargerCurrent 20
#define MENU_TEXT_ChargerCharged 21
#define MENU_TEXT_ChargerMode 22
#define MENU_TEXT_Light 23
#define MENU_TEXT_KeyAdValue 24
#define MENU_TEXT_Rs232Debug 25
#define MENU_TEXT_ConsumptionTotal 26
#define MENU_TEXT_Performance 27
#define MENU_TEXT_BatCap 28
#define MENU_TEXT_LedCurrent 29
#define MENU_TEXT_CalibRes 30
#define MENU_TEXT_Dcf77Level 31
#define MENU_TEXT_Pintest 32
#define MENU_TEXT_Logger 33
#define MENU_TEXT_Rebootcounter 34
#define MENU_TEXT_Elapsedtimemeter 35
#define MENU_TEXT_Rc5up 36
#define MENU_TEXT_Rc5down 37
#define MENU_TEXT_Rc5left 38
#define MENU_TEXT_Rc5right 39






#define MENU_USE_LABEL
#define MENU_USE_SUBWINDOW
#define MENU_USE_WINDOW
#define MENU_USE_SHORTCUT

#define MENU_USE_FONT_14
#define MENU_USE_FONT_15
#define MENU_USE_FONT_MAX 15
#define MENU_USE_UTF8

#define MENU_SDATA_5_1 2632
#define MENU_SDATA_35_1 2638
#define MENU_SDATA_78_1 2645
#define MENU_SDATA_36_1 2652
#define MENU_SDATA_3_1 2658
#define MENU_SDATA_33_1 2663
#define MENU_SDATA_34_1 2670
#define MENU_SDATA_62_1 2676
#define MENU_SDATA_86_1 2684
#define MENU_SDATA_7_1 2691
#define MENU_SDATA_39_1 2699
#define MENU_SDATA_40_1 2706
#define MENU_SDATA_41_1 2713
#define MENU_SDATA_42_1 2721
#define MENU_SDATA_43_1 2729
#define MENU_SDATA_44_1 2736
#define MENU_SDATA_80_1 2744
#define MENU_SDATA_81_1 2751
#define MENU_SDATA_83_1 2756
#define MENU_SDATA_84_1 2763
#define MENU_SDATA_85_1 2771
#define MENU_SDATA_1_1 2778
#define MENU_SDATA_51_1 2786
#define MENU_SDATA_61_1 2793
#define MENU_SDATA_59_1 2801
#define MENU_SDATA_4_1 2808
#define MENU_SDATA_29_1 2815
#define MENU_SDATA_28_1 2821
#define MENU_SDATA_31_1 2828
#define MENU_SDATA_52_1 2833
#define MENU_SDATA_53_1 2839
#define MENU_SDATA_68_1 2847
#define MENU_SDATA_70_1 2856
#define MENU_SDATA_72_1 2863
#define MENU_SDATA_73_1 2871
#define MENU_SDATA_76_1 2879
#define MENU_SDATA_92_1 2889
#define MENU_SDATA_93_1 2897
#define MENU_SDATA_100_1 2904
#define MENU_SDATA_101_1 2912
#define MENU_SDATA_56_1 2919
#define MENU_SDATA_67_1 2926
#define MENU_SDATA_64_1 2934
#define MENU_SDATA_65_1 2942
#define MENU_SDATA_66_1 2950

#endif

