/* Do not edit! This file is autogenerated by MenuEdit on 19-1-17 21:48:05*/

#ifndef MENU_INTERPRETER_CONFIG_H
#define MENU_INTERPRETER_CONFIG_H

#define USE16BITADDR

#define MENU_DATASIZE 3107
#define MENU_OBJECTS_MAX 6
#define MENU_LIST_MAX 0
#define MENU_TEXT_MAX 42
#define MENU_CHECKBOX_MAX 0
#define MENU_RADIOBUTTON_MAX 0
#define MENU_GFX_MAX 0
#define MENU_MULTIGFX_MAX 0
#define MENU_ACTION_MAX 87

#define MENU_SCREEN_X 28
#define MENU_SCREEN_Y 5

#define MENU_ACTION_DisplayUpdateOff 1
#define MENU_ACTION_Dcf77Off 2
#define MENU_ACTION_Dcf77On 3
#define MENU_ACTION_ShowClockOn 4
#define MENU_ACTION_ShowAlarmOn 5
#define MENU_ACTION_ShowAlarmadvancedOn 6
#define MENU_ACTION_ShowTimerOn 7
#define MENU_ACTION_ShowTemperatureOn 8
#define MENU_ACTION_PowersaveOn 9
#define MENU_ACTION_ShowDateOn 10
#define MENU_ACTION_AlarmDec 11
#define MENU_ACTION_AlarmInc 12
#define MENU_ACTION_AlarmNext 13
#define MENU_ACTION_AlarmAdvancedDec 14
#define MENU_ACTION_AlarmAdvancedInc 15
#define MENU_ACTION_AlarmAdvancedNext 16
#define MENU_ACTION_TimerDec 17
#define MENU_ACTION_TimerInc 18
#define MENU_ACTION_TimerStart 19
#define MENU_ACTION_ShowDispbrightOn 20
#define MENU_ACTION_ShowPowersavestartOn 21
#define MENU_ACTION_ShowPowersavestopOn 22
#define MENU_ACTION_ShowPowersaveweekOn 23
#define MENU_ACTION_BrightDec 24
#define MENU_ACTION_BrightInc 25
#define MENU_ACTION_BrightAutoToggle 26
#define MENU_ACTION_BrightAlwaysOff 27
#define MENU_ACTION_BrightAlwaysOn 28
#define MENU_ACTION_ClockShowSecOff 29
#define MENU_ACTION_ClockShowSecOn 30
#define MENU_ACTION_SummertimeAuto 31
#define MENU_ACTION_SummertimeOff 32
#define MENU_ACTION_SoundAutoOffDec 33
#define MENU_ACTION_SoundAutoOffInc 34
#define MENU_ACTION_SoundVolumeDec 35
#define MENU_ACTION_SoundVolumeInc 36
#define MENU_ACTION_SoundFreqDec 37
#define MENU_ACTION_SoundFreqInc 38
#define MENU_ACTION_RefreshDec 39
#define MENU_ACTION_RefreshInc 40
#define MENU_ACTION_Rfm12Dec 41
#define MENU_ACTION_Rfm12Inc 42
#define MENU_ACTION_Rfm12passkey100 43
#define MENU_ACTION_Rfm12passkey10 44
#define MENU_ACTION_Rfm12passkey1 45
#define MENU_ACTION_Rc5Dec 46
#define MENU_ACTION_Rc5Inc 47
#define MENU_ACTION_Rc5RecordUp 48
#define MENU_ACTION_PowersavestartDec 49
#define MENU_ACTION_PowersavestartInc 50
#define MENU_ACTION_PowersavestartNext 51
#define MENU_ACTION_PowersavestopDec 52
#define MENU_ACTION_PowersavestopInc 53
#define MENU_ACTION_PowersavestopNext 54
#define MENU_ACTION_PowersaveweekDec 55
#define MENU_ACTION_PowersaveweekInc 56
#define MENU_ACTION_PowersaveweekNext 57
#define MENU_ACTION_ShowVoltageOn 58
#define MENU_ACTION_ShowCurrentOn 59
#define MENU_ACTION_ShowChargedOn 60
#define MENU_ACTION_ShowLightOn 61
#define MENU_ACTION_ShowDCF77On 62
#define MENU_ACTION_Reboot 63
#define MENU_ACTION_ShowKeysOn 64
#define MENU_ACTION_ShowConsumptionOn 65
#define MENU_ACTION_ShowPerformanceOn 66
#define MENU_ACTION_PintestStart 67
#define MENU_ACTION_ShowLoggerOn 68
#define MENU_ACTION_ShowElapsedtimeOn 69
#define MENU_ACTION_ChargerDec 70
#define MENU_ACTION_ChargerInc 71
#define MENU_ACTION_Rs232Dec 72
#define MENU_ACTION_Rs232Inc 73
#define MENU_ACTION_BatCapDec 74
#define MENU_ACTION_BatCapInc 75
#define MENU_ACTION_LedCurrDec 76
#define MENU_ACTION_LedCurrInc 77
#define MENU_ACTION_CalRes46Dec 78
#define MENU_ACTION_CalRes46Inc 79
#define MENU_ACTION_Dcf77LevelDec 80
#define MENU_ACTION_Dcf77LevelInc 81
#define MENU_ACTION_KeylockLeave 82
#define MENU_ACTION_Rc5RecordDisable 83
#define MENU_ACTION_Rc5RecordDown 84
#define MENU_ACTION_Rc5RecordLeft 85
#define MENU_ACTION_Rc5RecordRight 86

#define MENU_TEXT_DcfValue 0
#define MENU_TEXT_Clock 1
#define MENU_TEXT_Date 2
#define MENU_TEXT_Alarm 3
#define MENU_TEXT_Alarmadvanced 4
#define MENU_TEXT_Timer 5
#define MENU_TEXT_Temperature 6
#define MENU_TEXT_Brightness 7
#define MENU_TEXT_BrigthAlways 8
#define MENU_TEXT_ShowSecs 9
#define MENU_TEXT_Summertime 10
#define MENU_TEXT_SoundAutoOffTime 11
#define MENU_TEXT_SoundVolume 12
#define MENU_TEXT_SoundFreq 13
#define MENU_TEXT_Refresh 14
#define MENU_TEXT_Rfm12enabled 15
#define MENU_TEXT_Rfm12passkey 16
#define MENU_TEXT_Rc5enabled 17
#define MENU_TEXT_Powersavestart 18
#define MENU_TEXT_Powersavestop 19
#define MENU_TEXT_Powersaveweekdays 20
#define MENU_TEXT_InputVoltage 21
#define MENU_TEXT_ChargerCurrent 22
#define MENU_TEXT_ChargerCharged 23
#define MENU_TEXT_ChargerMode 24
#define MENU_TEXT_Light 25
#define MENU_TEXT_KeyAdValue 26
#define MENU_TEXT_Rs232Debug 27
#define MENU_TEXT_ConsumptionTotal 28
#define MENU_TEXT_Performance 29
#define MENU_TEXT_BatCap 30
#define MENU_TEXT_LedCurrent 31
#define MENU_TEXT_CalibRes 32
#define MENU_TEXT_Dcf77Level 33
#define MENU_TEXT_Pintest 34
#define MENU_TEXT_Logger 35
#define MENU_TEXT_Rebootcounter 36
#define MENU_TEXT_Elapsedtimemeter 37
#define MENU_TEXT_Rc5up 38
#define MENU_TEXT_Rc5down 39
#define MENU_TEXT_Rc5left 40
#define MENU_TEXT_Rc5right 41






#define MENU_USE_LABEL
#define MENU_USE_SUBWINDOW
#define MENU_USE_WINDOW
#define MENU_USE_SHORTCUT

#define MENU_USE_FONT_14
#define MENU_USE_FONT_15
#define MENU_USE_FONT_MAX 15
#define MENU_USE_UTF8

#define MENU_SDATA_5_1 2766
#define MENU_SDATA_35_1 2772
#define MENU_SDATA_78_1 2779
#define MENU_SDATA_36_1 2786
#define MENU_SDATA_3_1 2792
#define MENU_SDATA_33_1 2797
#define MENU_SDATA_34_1 2804
#define MENU_SDATA_62_1 2810
#define MENU_SDATA_86_1 2818
#define MENU_SDATA_7_1 2825
#define MENU_SDATA_39_1 2833
#define MENU_SDATA_40_1 2840
#define MENU_SDATA_106_1 2847
#define MENU_SDATA_41_1 2854
#define MENU_SDATA_42_1 2862
#define MENU_SDATA_43_1 2870
#define MENU_SDATA_44_1 2877
#define MENU_SDATA_80_1 2885
#define MENU_SDATA_105_1 2892
#define MENU_SDATA_81_1 2900
#define MENU_SDATA_83_1 2905
#define MENU_SDATA_84_1 2912
#define MENU_SDATA_85_1 2920
#define MENU_SDATA_1_1 2927
#define MENU_SDATA_51_1 2935
#define MENU_SDATA_61_1 2942
#define MENU_SDATA_59_1 2950
#define MENU_SDATA_4_1 2957
#define MENU_SDATA_29_1 2964
#define MENU_SDATA_28_1 2970
#define MENU_SDATA_31_1 2977
#define MENU_SDATA_52_1 2982
#define MENU_SDATA_53_1 2988
#define MENU_SDATA_68_1 2996
#define MENU_SDATA_70_1 3005
#define MENU_SDATA_72_1 3012
#define MENU_SDATA_73_1 3020
#define MENU_SDATA_76_1 3028
#define MENU_SDATA_92_1 3038
#define MENU_SDATA_93_1 3046
#define MENU_SDATA_100_1 3053
#define MENU_SDATA_101_1 3061
#define MENU_SDATA_56_1 3068
#define MENU_SDATA_67_1 3075
#define MENU_SDATA_64_1 3083
#define MENU_SDATA_65_1 3091
#define MENU_SDATA_66_1 3099

#endif

